/*
 * generated by Xtext 2.22.0
 */
package csc498.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class Dsl2UiModule extends AbstractDsl2UiModule {

	public Dsl2UiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
