/**
 * generated by Xtext 2.22.0
 */
package csc498.dsl2.impl;

import csc498.dsl2.Down;
import csc498.dsl2.Dsl2Package;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Down</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class DownImpl extends CommandImpl implements Down
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DownImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return Dsl2Package.Literals.DOWN;
  }

} //DownImpl
