/**
 * generated by Xtext 2.22.0
 */
package csc498.dsl2.impl;

import csc498.dsl2.Dsl2Package;
import csc498.dsl2.Up;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Up</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class UpImpl extends CommandImpl implements Up
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected UpImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return Dsl2Package.Literals.UP;
  }

} //UpImpl
