/*
 * generated by Xtext 2.22.0
 */
package csc498.parser.antlr;

import com.google.inject.Inject;
import csc498.parser.antlr.internal.InternalDsl3Parser;
import csc498.services.Dsl3GrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class Dsl3Parser extends AbstractAntlrParser {

	@Inject
	private Dsl3GrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalDsl3Parser createParser(XtextTokenStream stream) {
		return new InternalDsl3Parser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Statemachine";
	}

	public Dsl3GrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(Dsl3GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
