/**
 * generated by Xtext 2.22.0
 */
package csc498.dsl1;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Contact</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link csc498.dsl1.Contact#getName <em>Name</em>}</li>
 *   <li>{@link csc498.dsl1.Contact#getEmail <em>Email</em>}</li>
 * </ul>
 *
 * @see csc498.dsl1.Dsl1Package#getContact()
 * @model
 * @generated
 */
public interface Contact extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see csc498.dsl1.Dsl1Package#getContact_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link csc498.dsl1.Contact#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Email</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Email</em>' attribute.
   * @see #setEmail(String)
   * @see csc498.dsl1.Dsl1Package#getContact_Email()
   * @model
   * @generated
   */
  String getEmail();

  /**
   * Sets the value of the '{@link csc498.dsl1.Contact#getEmail <em>Email</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Email</em>' attribute.
   * @see #getEmail()
   * @generated
   */
  void setEmail(String value);

} // Contact
