/**
 * generated by Xtext 2.22.0
 */
package csc498.dsl1;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see csc498.dsl1.Dsl1Factory
 * @model kind="package"
 * @generated
 */
public interface Dsl1Package extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "dsl1";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.Dsl1.csc498";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "dsl1";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  Dsl1Package eINSTANCE = csc498.dsl1.impl.Dsl1PackageImpl.init();

  /**
   * The meta object id for the '{@link csc498.dsl1.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see csc498.dsl1.impl.ModelImpl
   * @see csc498.dsl1.impl.Dsl1PackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Contacts</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__CONTACTS = 0;

  /**
   * The feature id for the '<em><b>Rsvps</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__RSVPS = 1;

  /**
   * The feature id for the '<em><b>Emails</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__EMAILS = 2;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link csc498.dsl1.impl.ContactImpl <em>Contact</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see csc498.dsl1.impl.ContactImpl
   * @see csc498.dsl1.impl.Dsl1PackageImpl#getContact()
   * @generated
   */
  int CONTACT = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTACT__NAME = 0;

  /**
   * The feature id for the '<em><b>Email</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTACT__EMAIL = 1;

  /**
   * The number of structural features of the '<em>Contact</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTACT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link csc498.dsl1.impl.RSVPImpl <em>RSVP</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see csc498.dsl1.impl.RSVPImpl
   * @see csc498.dsl1.impl.Dsl1PackageImpl#getRSVP()
   * @generated
   */
  int RSVP = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RSVP__NAME = 0;

  /**
   * The feature id for the '<em><b>Message</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RSVP__MESSAGE = 1;

  /**
   * The number of structural features of the '<em>RSVP</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RSVP_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link csc498.dsl1.impl.EmailImpl <em>Email</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see csc498.dsl1.impl.EmailImpl
   * @see csc498.dsl1.impl.Dsl1PackageImpl#getEmail()
   * @generated
   */
  int EMAIL = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EMAIL__NAME = 0;

  /**
   * The feature id for the '<em><b>Contacts</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EMAIL__CONTACTS = 1;

  /**
   * The feature id for the '<em><b>Message</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EMAIL__MESSAGE = 2;

  /**
   * The number of structural features of the '<em>Email</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EMAIL_FEATURE_COUNT = 3;


  /**
   * Returns the meta object for class '{@link csc498.dsl1.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see csc498.dsl1.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link csc498.dsl1.Model#getContacts <em>Contacts</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Contacts</em>'.
   * @see csc498.dsl1.Model#getContacts()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Contacts();

  /**
   * Returns the meta object for the containment reference list '{@link csc498.dsl1.Model#getRsvps <em>Rsvps</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Rsvps</em>'.
   * @see csc498.dsl1.Model#getRsvps()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Rsvps();

  /**
   * Returns the meta object for the containment reference list '{@link csc498.dsl1.Model#getEmails <em>Emails</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Emails</em>'.
   * @see csc498.dsl1.Model#getEmails()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Emails();

  /**
   * Returns the meta object for class '{@link csc498.dsl1.Contact <em>Contact</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Contact</em>'.
   * @see csc498.dsl1.Contact
   * @generated
   */
  EClass getContact();

  /**
   * Returns the meta object for the attribute '{@link csc498.dsl1.Contact#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see csc498.dsl1.Contact#getName()
   * @see #getContact()
   * @generated
   */
  EAttribute getContact_Name();

  /**
   * Returns the meta object for the attribute '{@link csc498.dsl1.Contact#getEmail <em>Email</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Email</em>'.
   * @see csc498.dsl1.Contact#getEmail()
   * @see #getContact()
   * @generated
   */
  EAttribute getContact_Email();

  /**
   * Returns the meta object for class '{@link csc498.dsl1.RSVP <em>RSVP</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>RSVP</em>'.
   * @see csc498.dsl1.RSVP
   * @generated
   */
  EClass getRSVP();

  /**
   * Returns the meta object for the attribute '{@link csc498.dsl1.RSVP#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see csc498.dsl1.RSVP#getName()
   * @see #getRSVP()
   * @generated
   */
  EAttribute getRSVP_Name();

  /**
   * Returns the meta object for the attribute '{@link csc498.dsl1.RSVP#getMessage <em>Message</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Message</em>'.
   * @see csc498.dsl1.RSVP#getMessage()
   * @see #getRSVP()
   * @generated
   */
  EAttribute getRSVP_Message();

  /**
   * Returns the meta object for class '{@link csc498.dsl1.Email <em>Email</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Email</em>'.
   * @see csc498.dsl1.Email
   * @generated
   */
  EClass getEmail();

  /**
   * Returns the meta object for the attribute '{@link csc498.dsl1.Email#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see csc498.dsl1.Email#getName()
   * @see #getEmail()
   * @generated
   */
  EAttribute getEmail_Name();

  /**
   * Returns the meta object for the reference list '{@link csc498.dsl1.Email#getContacts <em>Contacts</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Contacts</em>'.
   * @see csc498.dsl1.Email#getContacts()
   * @see #getEmail()
   * @generated
   */
  EReference getEmail_Contacts();

  /**
   * Returns the meta object for the attribute '{@link csc498.dsl1.Email#getMessage <em>Message</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Message</em>'.
   * @see csc498.dsl1.Email#getMessage()
   * @see #getEmail()
   * @generated
   */
  EAttribute getEmail_Message();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  Dsl1Factory getDsl1Factory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link csc498.dsl1.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see csc498.dsl1.impl.ModelImpl
     * @see csc498.dsl1.impl.Dsl1PackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Contacts</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__CONTACTS = eINSTANCE.getModel_Contacts();

    /**
     * The meta object literal for the '<em><b>Rsvps</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__RSVPS = eINSTANCE.getModel_Rsvps();

    /**
     * The meta object literal for the '<em><b>Emails</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__EMAILS = eINSTANCE.getModel_Emails();

    /**
     * The meta object literal for the '{@link csc498.dsl1.impl.ContactImpl <em>Contact</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see csc498.dsl1.impl.ContactImpl
     * @see csc498.dsl1.impl.Dsl1PackageImpl#getContact()
     * @generated
     */
    EClass CONTACT = eINSTANCE.getContact();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONTACT__NAME = eINSTANCE.getContact_Name();

    /**
     * The meta object literal for the '<em><b>Email</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONTACT__EMAIL = eINSTANCE.getContact_Email();

    /**
     * The meta object literal for the '{@link csc498.dsl1.impl.RSVPImpl <em>RSVP</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see csc498.dsl1.impl.RSVPImpl
     * @see csc498.dsl1.impl.Dsl1PackageImpl#getRSVP()
     * @generated
     */
    EClass RSVP = eINSTANCE.getRSVP();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RSVP__NAME = eINSTANCE.getRSVP_Name();

    /**
     * The meta object literal for the '<em><b>Message</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RSVP__MESSAGE = eINSTANCE.getRSVP_Message();

    /**
     * The meta object literal for the '{@link csc498.dsl1.impl.EmailImpl <em>Email</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see csc498.dsl1.impl.EmailImpl
     * @see csc498.dsl1.impl.Dsl1PackageImpl#getEmail()
     * @generated
     */
    EClass EMAIL = eINSTANCE.getEmail();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EMAIL__NAME = eINSTANCE.getEmail_Name();

    /**
     * The meta object literal for the '<em><b>Contacts</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EMAIL__CONTACTS = eINSTANCE.getEmail_Contacts();

    /**
     * The meta object literal for the '<em><b>Message</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EMAIL__MESSAGE = eINSTANCE.getEmail_Message();

  }

} //Dsl1Package
