/**
 * generated by Xtext 2.22.0
 */
package csc498.dsl1;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Email</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link csc498.dsl1.Email#getName <em>Name</em>}</li>
 *   <li>{@link csc498.dsl1.Email#getContacts <em>Contacts</em>}</li>
 *   <li>{@link csc498.dsl1.Email#getMessage <em>Message</em>}</li>
 * </ul>
 *
 * @see csc498.dsl1.Dsl1Package#getEmail()
 * @model
 * @generated
 */
public interface Email extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see csc498.dsl1.Dsl1Package#getEmail_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link csc498.dsl1.Email#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Contacts</b></em>' reference list.
   * The list contents are of type {@link csc498.dsl1.Contact}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Contacts</em>' reference list.
   * @see csc498.dsl1.Dsl1Package#getEmail_Contacts()
   * @model
   * @generated
   */
  EList<Contact> getContacts();

  /**
   * Returns the value of the '<em><b>Message</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Message</em>' attribute.
   * @see #setMessage(String)
   * @see csc498.dsl1.Dsl1Package#getEmail_Message()
   * @model
   * @generated
   */
  String getMessage();

  /**
   * Sets the value of the '{@link csc498.dsl1.Email#getMessage <em>Message</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Message</em>' attribute.
   * @see #getMessage()
   * @generated
   */
  void setMessage(String value);

} // Email
