/**
 * generated by Xtext 2.22.0
 */
package csc498.dsl1;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link csc498.dsl1.Model#getContacts <em>Contacts</em>}</li>
 *   <li>{@link csc498.dsl1.Model#getRsvps <em>Rsvps</em>}</li>
 *   <li>{@link csc498.dsl1.Model#getEmails <em>Emails</em>}</li>
 * </ul>
 *
 * @see csc498.dsl1.Dsl1Package#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Contacts</b></em>' containment reference list.
   * The list contents are of type {@link csc498.dsl1.Contact}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Contacts</em>' containment reference list.
   * @see csc498.dsl1.Dsl1Package#getModel_Contacts()
   * @model containment="true"
   * @generated
   */
  EList<Contact> getContacts();

  /**
   * Returns the value of the '<em><b>Rsvps</b></em>' containment reference list.
   * The list contents are of type {@link csc498.dsl1.RSVP}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rsvps</em>' containment reference list.
   * @see csc498.dsl1.Dsl1Package#getModel_Rsvps()
   * @model containment="true"
   * @generated
   */
  EList<RSVP> getRsvps();

  /**
   * Returns the value of the '<em><b>Emails</b></em>' containment reference list.
   * The list contents are of type {@link csc498.dsl1.Email}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Emails</em>' containment reference list.
   * @see csc498.dsl1.Dsl1Package#getModel_Emails()
   * @model containment="true"
   * @generated
   */
  EList<Email> getEmails();

} // Model
