/*
 * generated by Xtext 2.22.0
 */
package csc498.parser.antlr;

import com.google.inject.Inject;
import csc498.parser.antlr.internal.InternalDsl2Parser;
import csc498.services.Dsl2GrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class Dsl2Parser extends AbstractAntlrParser {

	@Inject
	private Dsl2GrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalDsl2Parser createParser(XtextTokenStream stream) {
		return new InternalDsl2Parser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public Dsl2GrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(Dsl2GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
