/*
 * generated by Xtext 2.22.0
 */
package csc498.ui;

import com.google.inject.Injector;
import csc498.dsl1.ui.internal.Dsl1Activator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class Dsl1ExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(Dsl1Activator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		Dsl1Activator activator = Dsl1Activator.getInstance();
		return activator != null ? activator.getInjector(Dsl1Activator.CSC498_DSL1) : null;
	}

}
