/*
 * generated by Xtext 2.22.0
 */
package csc498.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class Dsl1UiModule extends AbstractDsl1UiModule {

	public Dsl1UiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
