/**
 * generated by Xtext 2.22.0
 */
package csc498.dsl2;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see csc498.dsl2.Dsl2Factory
 * @model kind="package"
 * @generated
 */
public interface Dsl2Package extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "dsl2";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.Dsl2.csc498";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "dsl2";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  Dsl2Package eINSTANCE = csc498.dsl2.impl.Dsl2PackageImpl.init();

  /**
   * The meta object id for the '{@link csc498.dsl2.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see csc498.dsl2.impl.ModelImpl
   * @see csc498.dsl2.impl.Dsl2PackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Games</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__GAMES = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link csc498.dsl2.impl.GameImpl <em>Game</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see csc498.dsl2.impl.GameImpl
   * @see csc498.dsl2.impl.Dsl2PackageImpl#getGame()
   * @generated
   */
  int GAME = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME__NAME = 0;

  /**
   * The feature id for the '<em><b>Commands</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME__COMMANDS = 1;

  /**
   * The number of structural features of the '<em>Game</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link csc498.dsl2.impl.CommandImpl <em>Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see csc498.dsl2.impl.CommandImpl
   * @see csc498.dsl2.impl.Dsl2PackageImpl#getCommand()
   * @generated
   */
  int COMMAND = 2;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND__VALUE = 0;

  /**
   * The number of structural features of the '<em>Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link csc498.dsl2.impl.UpImpl <em>Up</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see csc498.dsl2.impl.UpImpl
   * @see csc498.dsl2.impl.Dsl2PackageImpl#getUp()
   * @generated
   */
  int UP = 3;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UP__VALUE = COMMAND__VALUE;

  /**
   * The number of structural features of the '<em>Up</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UP_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link csc498.dsl2.impl.DownImpl <em>Down</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see csc498.dsl2.impl.DownImpl
   * @see csc498.dsl2.impl.Dsl2PackageImpl#getDown()
   * @generated
   */
  int DOWN = 4;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOWN__VALUE = COMMAND__VALUE;

  /**
   * The number of structural features of the '<em>Down</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOWN_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link csc498.dsl2.impl.RightImpl <em>Right</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see csc498.dsl2.impl.RightImpl
   * @see csc498.dsl2.impl.Dsl2PackageImpl#getRight()
   * @generated
   */
  int RIGHT = 5;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RIGHT__VALUE = COMMAND__VALUE;

  /**
   * The number of structural features of the '<em>Right</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RIGHT_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link csc498.dsl2.impl.LeftImpl <em>Left</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see csc498.dsl2.impl.LeftImpl
   * @see csc498.dsl2.impl.Dsl2PackageImpl#getLeft()
   * @generated
   */
  int LEFT = 6;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LEFT__VALUE = COMMAND__VALUE;

  /**
   * The number of structural features of the '<em>Left</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LEFT_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 0;


  /**
   * Returns the meta object for class '{@link csc498.dsl2.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see csc498.dsl2.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link csc498.dsl2.Model#getGames <em>Games</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Games</em>'.
   * @see csc498.dsl2.Model#getGames()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Games();

  /**
   * Returns the meta object for class '{@link csc498.dsl2.Game <em>Game</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Game</em>'.
   * @see csc498.dsl2.Game
   * @generated
   */
  EClass getGame();

  /**
   * Returns the meta object for the attribute '{@link csc498.dsl2.Game#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see csc498.dsl2.Game#getName()
   * @see #getGame()
   * @generated
   */
  EAttribute getGame_Name();

  /**
   * Returns the meta object for the containment reference list '{@link csc498.dsl2.Game#getCommands <em>Commands</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Commands</em>'.
   * @see csc498.dsl2.Game#getCommands()
   * @see #getGame()
   * @generated
   */
  EReference getGame_Commands();

  /**
   * Returns the meta object for class '{@link csc498.dsl2.Command <em>Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Command</em>'.
   * @see csc498.dsl2.Command
   * @generated
   */
  EClass getCommand();

  /**
   * Returns the meta object for the attribute '{@link csc498.dsl2.Command#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see csc498.dsl2.Command#getValue()
   * @see #getCommand()
   * @generated
   */
  EAttribute getCommand_Value();

  /**
   * Returns the meta object for class '{@link csc498.dsl2.Up <em>Up</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Up</em>'.
   * @see csc498.dsl2.Up
   * @generated
   */
  EClass getUp();

  /**
   * Returns the meta object for class '{@link csc498.dsl2.Down <em>Down</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Down</em>'.
   * @see csc498.dsl2.Down
   * @generated
   */
  EClass getDown();

  /**
   * Returns the meta object for class '{@link csc498.dsl2.Right <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Right</em>'.
   * @see csc498.dsl2.Right
   * @generated
   */
  EClass getRight();

  /**
   * Returns the meta object for class '{@link csc498.dsl2.Left <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Left</em>'.
   * @see csc498.dsl2.Left
   * @generated
   */
  EClass getLeft();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  Dsl2Factory getDsl2Factory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link csc498.dsl2.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see csc498.dsl2.impl.ModelImpl
     * @see csc498.dsl2.impl.Dsl2PackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Games</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__GAMES = eINSTANCE.getModel_Games();

    /**
     * The meta object literal for the '{@link csc498.dsl2.impl.GameImpl <em>Game</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see csc498.dsl2.impl.GameImpl
     * @see csc498.dsl2.impl.Dsl2PackageImpl#getGame()
     * @generated
     */
    EClass GAME = eINSTANCE.getGame();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GAME__NAME = eINSTANCE.getGame_Name();

    /**
     * The meta object literal for the '<em><b>Commands</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GAME__COMMANDS = eINSTANCE.getGame_Commands();

    /**
     * The meta object literal for the '{@link csc498.dsl2.impl.CommandImpl <em>Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see csc498.dsl2.impl.CommandImpl
     * @see csc498.dsl2.impl.Dsl2PackageImpl#getCommand()
     * @generated
     */
    EClass COMMAND = eINSTANCE.getCommand();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMMAND__VALUE = eINSTANCE.getCommand_Value();

    /**
     * The meta object literal for the '{@link csc498.dsl2.impl.UpImpl <em>Up</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see csc498.dsl2.impl.UpImpl
     * @see csc498.dsl2.impl.Dsl2PackageImpl#getUp()
     * @generated
     */
    EClass UP = eINSTANCE.getUp();

    /**
     * The meta object literal for the '{@link csc498.dsl2.impl.DownImpl <em>Down</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see csc498.dsl2.impl.DownImpl
     * @see csc498.dsl2.impl.Dsl2PackageImpl#getDown()
     * @generated
     */
    EClass DOWN = eINSTANCE.getDown();

    /**
     * The meta object literal for the '{@link csc498.dsl2.impl.RightImpl <em>Right</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see csc498.dsl2.impl.RightImpl
     * @see csc498.dsl2.impl.Dsl2PackageImpl#getRight()
     * @generated
     */
    EClass RIGHT = eINSTANCE.getRight();

    /**
     * The meta object literal for the '{@link csc498.dsl2.impl.LeftImpl <em>Left</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see csc498.dsl2.impl.LeftImpl
     * @see csc498.dsl2.impl.Dsl2PackageImpl#getLeft()
     * @generated
     */
    EClass LEFT = eINSTANCE.getLeft();

  }

} //Dsl2Package
