/**
 * generated by Xtext 2.22.0
 */
package csc498.dsl2;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link csc498.dsl2.Model#getGames <em>Games</em>}</li>
 * </ul>
 *
 * @see csc498.dsl2.Dsl2Package#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Games</b></em>' containment reference list.
   * The list contents are of type {@link csc498.dsl2.Game}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Games</em>' containment reference list.
   * @see csc498.dsl2.Dsl2Package#getModel_Games()
   * @model containment="true"
   * @generated
   */
  EList<Game> getGames();

} // Model
