/**
 * generated by Xtext 2.22.0
 */
package csc498.dsl2;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Right</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see csc498.dsl2.Dsl2Package#getRight()
 * @model
 * @generated
 */
public interface Right extends Command
{
} // Right
