/*
 * generated by Xtext 2.22.0
 */
package csc498.ui;

import com.google.inject.Injector;
import csc498.dsl3.ui.internal.Dsl3Activator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class Dsl3ExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(Dsl3Activator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		Dsl3Activator activator = Dsl3Activator.getInstance();
		return activator != null ? activator.getInjector(Dsl3Activator.CSC498_DSL3) : null;
	}

}
