/*
 * generated by Xtext 2.22.0
 */
package csc498.ui.tests;

import com.google.inject.Injector;
import csc498.dsl3.ui.internal.Dsl3Activator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class Dsl3UiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return Dsl3Activator.getInstance().getInjector("csc498.Dsl3");
	}

}
