/*
 * generated by Xtext 2.22.0
 */
package csc498.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDsl3ScopeProvider extends DelegatingScopeProvider {
}
