/*
 * generated by Xtext 2.22.0
 */
package csc498;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class Dsl3StandaloneSetup extends Dsl3StandaloneSetupGenerated {

	public static void doSetup() {
		new Dsl3StandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
