/*
 * generated by Xtext 2.22.0
 */
package csc498;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class Dsl3RuntimeModule extends AbstractDsl3RuntimeModule {
}
